### ISSUE TITLE
Vulnerabilities with 1 introduced and 2 fixed versions: GO-2021-0068

### ISSUE THREAD

**Issue by ldej** [google/osv#421]
How to interpret this vulnerability with one introduced and two fixed versions?

https://osv.dev/vulnerability/GO-2021-0068

**Comment by oliverchang** [comment]
Thanks for flagging! 

The [interpretation](https://ossf.github.io/osv-schema/#evaluation) here would be that everything after 1.14.14 is considered fixed. It seems that it was reintroduced in the 1.15 branch somewhere before being fixed in 1.15.7.

This seems like incorrect data: could you please file an issue in https://github.com/golang/vulndb ?

**Comment by oliverchang** [comment]
This is now fixed upstream!
