### ISSUE TITLE
Inconsistent states of issues in oss-fuzz and OSV

### ISSUE THREAD

**Issue by rlohning** [google/osv#88]
Hi,

I just had a first look at OSV and have to say that it really looks like a great help to me. Thank you very much for starting this.

Unfortunately, I noticed that at least one issue's states are inconsistent in oss-fuzz and OSV:
[oss-fuzz 24266](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24266) is "Verified" since January 5th, so all versions greater than v6.0.0 should be fixed, but the resulting [OSV-2020-902](https://osv.dev/vulnerability/OSV-2020-902) still reads "Not fixed". Could you please double-check this?

In case it matters: The issue was found in Qt built from branch 5.15. It was marked "Verified" immediately after I moved to building from the dev branch.

Cheers,
Robert

**Comment by oliverchang** [comment]
Hi @rlohning 

Thanks for your interest in OSV!

Indeed it looks like our infrastructure was having trouble with determining the fix, because the branch changed. I created https://github.com/google/oss-fuzz/pull/5478 to address this.

We are also **very** close to publishing our OSV data in a way that lets anyone can contribute changes, so that in the future you can just submit a PR to fix up any inaccuracies with our data.

**Comment by rlohning** [comment]
Thank you! :-)

**Comment by oliverchang** [comment]
OSV-2020-902 now reads as fixed and we've also released https://github.com/google/oss-fuzz-vulns where anyone can contribute corrections. So I'm closing this :)

**Comment by rlohning** [comment]
Thank you for handling this. In [pull/1](https://github.com/google/oss-fuzz-vulns/pull/1), I try to correct the affected versions.
